### ISSUE TITLE
Duplicate files in documentation directory, only differing in case

### ISSUE THREAD

**Issue by pschneider1968** [TheAlgorithms/R#120]
When cloning the repo to my Windows machine, I received the following warning message:

```
Cloning into 'Algorithms-in-R'...
remote: Enumerating objects: 984, done.
remote: Counting objects: 100% (984/984), done.
remote: Compressing objects: 100% (424/424), done.
remote: Total 984 (delta 532), reused 984 (delta 532), pack-reused 0
Receiving objects: 100% (984/984), 927.20 KiB | 27.27 MiB/s, done.
Resolving deltas: 100% (532/532), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'documentation/ANN.md'
  'documentation/ann.md'
  'documentation/K_Folds.md'
  'documentation/k_folds.md'
  'documentation/kmeans_raw_R.md'
  'documentation/kmeans_raw_r.md'
  'documentation/KNN.md'
  'documentation/knn.md'
  'documentation/linearRegressionRawR.md'
  'documentation/linearregressionrawr.md'
  'documentation/SVM.md'
  'documentation/svm.md'

Peter@bolide MINGW64 /c/repos/Learn/Algorithms
$

```
So it seems to me these files are duplicated and only differing in case. However from each pair, one of them has a newer commit. So you might want to check these changes to see whether they have been applied to the right files, or correct the case of the most recent file and delete the older other one.

These changes are mostly from #88 it seems.

**Comment by siriak** [comment]
Hi, thanks for reporting that! Do you want to make a PR to fix that or somebody else can pick up this issue? I think it should be safe to just remove older files.

**Comment by pschneider1968** [comment]
Sure I can do that! What case would you prefer for the correct version of the affected files? Should they be in mixed/upper case, as they were before, or would you like them to be all lower case? The latter would be inconsistent with the remainder of the documentation directory, however...

**Comment by siriak** [comment]
I'm thinking of having them all lowercase. This doesn't seem to be too inconsistent, though. There are other files that are lowercase and don't have PascalCase counterparts. Maybe you could rename other files to match the naming scheme?

**Comment by pschneider1968** [comment]
At first glance, I thought that all files in the documentation directory were just normal, manually written and edited documentation files.

But now I dug a little bit deeper to understand the issue, and learnt that these files are autogenerated by a Github workflow. What was specifically changed in #88 was that a new R script .github/scripts/doc_builder.r has been added that does this job, and does it differently than before, when this functionality was still in .github/workflows/documentation_workflow.yml

So I've now come to think that manually changing stuff in the documentation directory is pointless because of this. I guess when a maintainer commits to the master branch and the Github workflows are triggered, all documentation files are re-generated.

However: this won't delete the old ones. Maybe this could be added to the workflow? I'm not sure about this, as I'm not very familiar with GH workflows...

**Comment by siriak** [comment]
I've added removal of old files in #121, but it seems that not all of them are autogenerated (just based on the number of removed and added files). HTML files are not generated either. Unfortunately, I don't have time to dig in at the moment. Maybe you could check what's going on? Where HTML files are from and whether or not there is manual documentation?

**Comment by siriak** [comment]
I think I might have fixed it. In #121 all but 2 files compiled successfully. At least it's not a systemic error now. Please let me know if it looks good to you.

**Comment by pschneider1968** [comment]
I tried your changes in my fork, and can confirm that all but 2 scripts now run successfully and generate output files in the documentation directory.

The two remaining errors I see are these:

```

processing file: ../classification_algorithms/decision_tree.Rmd
1/3                  
2/3 [unnamed-chunk-1]
3/3                  
output file: decision_tree.md
Error compiling: Error in parse(text = x, keep.source = TRUE): <text>:59:45: unexpected symbol
58: 
59: x <- data[,!(names(data) %in% drop_columns)]y
                                                ^

processing file: ../regression_algorithms/ann.Rmd
1/3                  
2/3 [unnamed-chunk-1]
3/3                  
output file: ann.md
Error compiling: Error in parse(text = x, keep.source = TRUE): <text>:59:45: unexpected symbol
58: 
59: x <- data[,!(names(data) %in% drop_columns)]y
                                                ^

```

But I have no idea what causes them or how to fix 😔

But anyway, nice to see some progress!

**Comment by pschneider1968** [comment]
Now as #121 was merged, I think this issue can be closed.
