### ISSUE TITLE
Where are the sample datasets?

### ISSUE THREAD

**Issue by hao203** [TheAlgorithms/R#39]
I want to run the code in Rstudio, but all the data are not found.
Anyone can tell me where to download the datasets?

Thank you

**Comment by hao203** [comment]
Anyone here?

**Comment by eshom** [comment]
This issue illustrates a prevalent issue where many scripts aren't reproducible. At the very least scripts should be self contained. Either built-in in data (there are many) can be used as an example, or easily downloadable public data could be read to memory and used that way.

**Comment by imsaxenashivam** [comment]
> I want to run the code in Rstudio, but all the data are not found. Anyone can tell me where to download the datasets?
> 
> Thank you

Could you please elaborate more about the issue ??
Thank you

**Comment by siriak** [comment]
This issue is tracked in #61
