### ISSUE TITLE
Add documentation in the code (something similar to Doxygen)

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/R#59]
Something similar to an issue in the Julia repository. See https://github.com/TheAlgorithms/Julia/issues/7.

**Comment by eshom** [comment]
This might be possible using the `knitr` package. Specifically with `knitr::spin()`, which can convert R scripts to documents. I'll have to play around with it to know better.

**Comment by Panquesito7** [comment]
That sounds fine, I guess. I don't really know too much about R, but we could start working on it. For PR reviewing, I could do documentation reviews, and someone else can do the code reviews if that's fine for you. 🙂

**Comment by eshom** [comment]
@Panquesito7 
I've made a small repository demonstrating how documentation could be generated from scripts using the `knitr` package.
https://github.com/eshom/R-knitspin-test
The documentation generation could be automated using github actions. I'm not too familiar with it, so github actions aren't included in the example currently.

Thoughts?

**Comment by Panquesito7** [comment]
Looks great! Great job, @eshom! And about the GitHub Actions thingy, I could try to work on it. 🙂
