### ISSUE TITLE
Multiple sequence alignment using R

### ISSUE THREAD

**Issue by shreejyoti** [TheAlgorithms/R#76]
myAlignment<- msaClustalW("mydata", type = "dna")
use default substitution matrix
Error in convertAlnRows(result$msa, type) : There is an invalid aln file!

I'm facing issue using the above code. I want to perform multiple sequence alignment on csv or fasta file. but getting this error. please help me to solve it.

**Comment by Preetiraj3697** [comment]
!assign

**Comment by Preetiraj3697** [comment]
```R
library(Biostrings)

#Set the file path and name
file_path <- "mydata.fasta"

# Perform the multiple sequence alignment using ClustalW
myAlignment <- msaClustalW(file_path, filetype = "fasta", type = "dna")
```

**Comment by siriak** [comment]
@Preetiraj3697 please create a PR with the fix

**Comment by Preetiraj3697** [comment]
@siriak How to create a PR

**Comment by siriak** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by siriak** [comment]
@shreejyoti this doesn't look like code from this repository, so it doesn't need to be fixed. Please see @Preetiraj3697's answer

**Comment by shreejyoti** [comment]
Thank you for solving!

**Comment by oliver7423** [comment]
hi i hope this thread is online.

i have the same problem and this is my coding

AlignNeeded = TRUE # The program reads fasta file and aligns it
if (AlignNeeded) {
  
file <- readDNAStringSet(fname)#for reading multiple DNA sequences from msa package
file
}

cb<- msa(file) # multiple sequence alignment from msa package 
cb

Error in convertAlnRows(result$msa, type) : There is an invalid aln file!

Idk what to do

**Comment by oliver7423** [comment]
> hi i hope this thread is online.
> 
> i have the same problem and this is my coding
> 
> AlignNeeded = TRUE # The program reads fasta file and aligns it if (AlignNeeded) {
> 
> file <- readDNAStringSet(fname)#for reading multiple DNA sequences from msa package file }
> 
> cb<- msa(file) # multiple sequence alignment from msa package cb
> 
> Error in convertAlnRows(result$msa, type) : There is an invalid aln file!
> 
> Idk what to do

btw this is from R studio
